### ISSUE TITLE
Requiremetns.txt @ եթե ճիշտ հասկացա ձեռով էս սարքել

### ISSUE THREAD

**Issue by HaykTarkhanyan** [aprikyan/google-books-downloader#2]
time module @ orinaki hamar standard lib um ka, iran petq chi install anel, regex nel vayte(vstah chem)

**Comment by HaykTarkhanyan** [comment]
Nuynnel os @

**Comment by aprikyan** [comment]
չէի ֆայմել 👀

re-ն հա, բայց regex-ը չէ
