### ISSUE TITLE
cannot find chrome binary 

### ISSUE THREAD

**Issue by nonvieri** [aprikyan/google-books-downloader#7]
message: unknown error: cannot find chrome binary

**Comment by aprikyan** [comment]
Chrome binary is the "chrome.exe" executable which you run when opening your local Chrome. To solve the issue, try the following:

1. Ensure that you have Google Chrome installed on your computer.
2. If you do, find the address of the "chrome.exe" executable. On my PC, it is stored in "C:\Program Files (x86)\Google\Chrome\Application".
3. In `gbd.py`, on line 240 after `chrome_options = Options()` add the following line:
`chrome_options.binary_location = r"PATH_TO_CHROME.EXE"`
or, as in my case,
`chrome_options.binary_location = r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"`

**Comment by nonvieri** [comment]
now i get this…
![image](https://user-images.githubusercontent.com/46636729/109356943-2a7d9980-7860-11eb-8426-8966710438b9.png)

**Comment by georgetian3** [comment]
> now i get this…
> ![image](https://user-images.githubusercontent.com/46636729/109356943-2a7d9980-7860-11eb-8426-8966710438b9.png)

This issue can be fixed by replacing `chromedriver.exe` with an updated version found [here](https://chromedriver.chromium.org/downloads).
